### ISSUE TITLE
A lot of boilerplate code

### ISSUE THREAD

**Issue by amirkhaniansev** [DavidPetr/OS_Projects#1]
https://github.com/DavidPetr/OS_Projects/blob/0d98b8e5182af91ef013b1e92d794b223c034b03/Producer_Consumer/Producer_Consumer/Source.cpp#L43-L100

Instead you could have a function which will do the checking.
The possible signature and implementation will be

```
assert(void* actual_value, wchar_t* msg, int exit_code) 
{
    if(actual_value == NULL)
    {
         wprintf(msg); 
         MYPerror(); 
 	 exit(exit_code); 
    }
}
```

and call it in initialize()
for example: 

`` assert(producers = malloc(sizeof(HANDLE)*Producers_Count), AllocateError, 1); ``

No need for explicit casts this is C bro, not C++ and even more it is dangerous to do cast after malloc(). For more information please see:
[http://c-faq.com/malloc/mallocnocast.html](url)

**Comment by DavidPetr** [comment]
Thanks for opening issue. I really felt uncomfortable when write program like that, because it was too unreadable. I modify it, and now it looks so cute :D:
About explicit cast you are right that "No need for explicit cast in C", but I write program in C++, because my computer language is russian, and MYPerror wprints error in russian, so I need to include <iostream>,in order to I can use setlocale() function;
